using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenApi.Dto
{
    class REAL10004_Data
    {
        public String 호가시간 = "";
        public int 매도호가1 = 0;
        public int 매도호가수량1 = 0;
        public int 매도호가직전대비1 = 0;
        public int 매수호가1 = 0;
        public int 매수호가수량1 = 0;
        public int 매수호가직전대비1 = 0;
        public int 매도호가2 = 0;
        public int 매도호가수량2 = 0;
        public int 매도호가직전대비2 = 0;
        public int 매수호가2 = 0;
        public int 매수호가수량2 = 0;
        public int 매수호가직전대비2 = 0;
        public int 매도호가3 = 0;
        public int 매도호가수량3 = 0;
        public int 매도호가직전대비3 = 0;
        public int 매수호가3 = 0;
        public int 매수호가수량3 = 0;
        public int 매수호가직전대비3 = 0;
        public int 매도호가4 = 0;
        public int 매도호가수량4 = 0;
        public int 매도호가직전대비4 = 0;
        public int 매수호가4 = 0;
        public int 매수호가수량4 = 0;
        public int 매수호가직전대비4 = 0;
        public int 매도호가5 = 0;
        public int 매도호가수량5 = 0;
        public int 매도호가직전대비5 = 0;
        public int 매수호가5 = 0;
        public int 매수호가수량5 = 0;
        public int 매수호가직전대비5 = 0;
        public int 매도호가6 = 0;
        public int 매도호가수량6 = 0;
        public int 매도호가직전대비6 = 0;
        public int 매수호가6 = 0;
        public int 매수호가수량6 = 0;
        public int 매수호가직전대비6 = 0;
        public int 매도호가7 = 0;
        public int 매도호가수량7 = 0;
        public int 매도호가직전대비7 = 0;
        public int 매수호가7 = 0;
        public int 매수호가수량7 = 0;
        public int 매수호가직전대비7 = 0;
        public int 매도호가8 = 0;
        public int 매도호가수량8 = 0;
        public int 매도호가직전대비8 = 0;
        public int 매수호가8 = 0;
        public int 매수호가수량8 = 0;
        public int 매수호가직전대비8 = 0;
        public int 매도호가9 = 0;
        public int 매도호가수량9 = 0;
        public int 매도호가직전대비9 = 0;
        public int 매수호가9 = 0;
        public int 매수호가수량9 = 0;
        public int 매수호가직전대비9 = 0;
        public int 매도호가10 = 0;
        public int 매도호가수량10 = 0;
        public int 매도호가직전대비10 = 0;
        public int 매수호가10 = 0;
        public int 매수호가수량10 = 0;
        public int 매수호가직전대비10 = 0;
        public int 매도호가총잔량 = 0;
        public int 매도호가총잔량직전대비 = 0;
        public int 매수호가총잔량 = 0;
        public int 매수호가총잔량직전대비 = 0;
        public int 예상체결가 = 0;
        public int 예상체결수량 = 0;
        public int 순매수잔량 = 0;
        public float 매수비율 = 0;
        public int 순매도잔량 = 0;
        public float 매도비율 = 0;
        public int 예상체결가전일종가대비 = 0;
        public float 예상체결가전일종가대비등락율 = 0;
        public int 예상체결가전일종가대비기호 = 0;
        public int 예상체결가1 = 0;
        public int 예상체결량1 = 0;
        public int 예상체결가전일대비기호1 = 0;
        public int 예상체결가전일대비1 = 0;
        public float 예상체결가전일대비등락율1 = 0;
        public int LP매도호가수량1 = 0;
        public int LP매수호가수량1 = 0;
        public int LP매도호가수량2 = 0;
        public int LP매수호가수량2 = 0;
        public int LP매도호가수량3 = 0;
        public int LP매수호가수량3 = 0;
        public int LP매도호가수량4 = 0;
        public int LP매수호가수량4 = 0;
        public int LP매도호가수량5 = 0;
        public int LP매수호가수량5 = 0;
        public int LP매도호가수량6 = 0;
        public int LP매수호가수량6 = 0;
        public int LP매도호가수량7 = 0;
        public int LP매수호가수량7 = 0;
        public int LP매도호가수량8 = 0;
        public int LP매수호가수량8 = 0;
        public int LP매도호가수량9 = 0;
        public int LP매수호가수량9 = 0;
        public int LP매도호가수량10 = 0;
        public int LP매수호가수량10 = 0;
        public int 누적거래량 = 0;
        public float 전일거래량대비예상체결률 = 0;
        public String 장운영구분 = "";
        public String 투자자별ticker = "";
        public String 종목코드 = "";
        public String RealName = "";
    }
}
